//! Defines the network protocol and data structures for communication between zzping services.

use anyhow::{Result, anyhow};
use serde::{Deserialize, Serialize};
use tokio::io::{AsyncReadExt, AsyncWriteExt};

/// A command sent from the GUI to the database.
#[derive(Debug, PartialEq, Eq, Clone, Copy)]
#[repr(u16)]
pub enum QueryCommand {
    GetLastMinute = 0,
}

impl QueryCommand {
    pub fn from_u16(value: u16) -> Option<Self> {
        match value {
            0 => Some(QueryCommand::GetLastMinute),
            _ => None,
        }
    }
}

/// A message sent by the collector to the database upon establishing a connection.
///
/// This handshake allows the collector to identify itself and the target it will be
/// pinging for the duration of the connection.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ClientHandshake {
    pub source_hostname: String,
    pub target: std::net::IpAddr,
}

/// The fundamental data structure for a single ping measurement.
///
/// This is the canonical format for data transfer between the collector and the database.
/// It is designed to be simple and efficient for JSON serialization.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
pub struct RawDataRecord {
    /// The timestamp when the ping was sent, as a UNIX timestamp in nanoseconds.
    ///
    /// This value is generated by the collector and represents the `Instant` the ICMP
    /// packet was sent, relative to a monotonic clock started at the beginning of the
    /// collector's session. The database service should treat this as a relative value
    /// and store it alongside an absolute timestamp for the session.
    pub sent_nanos: u64,
    /// The round-trip time in nanoseconds.
    ///
    /// If the packet was lost, this value will be `u64::MAX`. This is a sentinel value
    /// used to indicate packet loss, as `Option<u64>` would be less efficient for
    /// serialization and storage in the `chunked_v1` format.
    pub rtt_nanos: u64,
}

/// Writes a length-prefixed, bincode-serialized `RawDataRecord` to an async writer.
///
/// This function implements the sending side of the simple zzping network protocol.
/// The protocol is designed to be easy to implement in various clients and servers.
///
/// # Protocol Format
/// - 4 bytes: `u32` length of the following bincode payload, encoded in big-endian format.
/// - N bytes: The `RawDataRecord` struct, serialized using bincode.
///
/// # Arguments
/// * `stream` - An async writer, typically a `TcpStream`.
/// * `record` - The `RawDataRecord` to be sent.
pub async fn write_record<W: AsyncWriteExt + Unpin>(
    stream: &mut W,
    record: &RawDataRecord,
) -> Result<()> {
    let data = bincode::serialize(record)?;
    stream.write_u32(data.len() as u32).await?;
    stream.write_all(&data).await?;
    Ok(())
}

/// Reads a length-prefixed, bincode-serialized `RawDataRecord` from an async reader.
///
/// This function implements the receiving side of the simple zzping network protocol.
/// It handles reading the length prefix first, then reading the exact number of bytes
/// for the payload before deserializing.
///
/// # Returns
/// * `Ok(Some(RawDataRecord))` - If a record was successfully read and deserialized.
/// * `Ok(None)` - If the stream was closed cleanly by the peer (EOF).
/// * `Err(anyhow::Error)` - If there was an I/O error or a deserialization error.
pub async fn read_record<R: AsyncReadExt + Unpin>(stream: &mut R) -> Result<Option<RawDataRecord>> {
    let len = match stream.read_u32().await {
        Ok(len) => len,
        Err(e) if e.kind() == std::io::ErrorKind::UnexpectedEof => return Ok(None),
        Err(e) => return Err(e.into()),
    };

    if len == 0 {
        // This could be a keep-alive or a bug, but we'll treat it as a graceful end for now.
        return Ok(None);
    }

    let mut buffer = vec![0; len as usize];
    stream.read_exact(&mut buffer).await?;
    let record: RawDataRecord = bincode::deserialize(&buffer)?;
    Ok(Some(record))
}

/// Writes a batch of `RawDataRecord`s to an async writer using the same
/// length-prefixed bincode format.
///
/// This is used by the database to send query results to the GUI.
pub async fn write_records_batch<W: AsyncWriteExt + Unpin>(
    stream: &mut W,
    records: &[RawDataRecord],
) -> Result<()> {
    let data = bincode::serialize(records)?;
    stream.write_u32(data.len() as u32).await?;
    stream.write_all(&data).await?;
    Ok(())
}

/// Reads a batch of `RawDataRecord`s from an async reader.
///
/// This is used by the GUI to receive query results from the database.
pub async fn read_records_batch<R: AsyncReadExt + Unpin>(
    stream: &mut R,
) -> Result<Option<Vec<RawDataRecord>>> {
    let len = match stream.read_u32().await {
        Ok(len) => len,
        Err(e) if e.kind() == std::io::ErrorKind::UnexpectedEof => return Ok(None),
        Err(e) => return Err(e.into()),
    };

    if len == 0 {
        return Ok(Some(Vec::new())); // An empty batch is valid
    }

    let mut buffer = vec![0; len as usize];
    stream.read_exact(&mut buffer).await?;
    let records: Vec<RawDataRecord> = bincode::deserialize(&buffer)?;
    Ok(Some(records))
}

/// Writes a `QueryCommand` to an async writer.
pub async fn write_command<W: AsyncWriteExt + Unpin>(
    stream: &mut W,
    command: &QueryCommand,
) -> Result<()> {
    stream.write_u16(*command as u16).await?;
    Ok(())
}

/// Reads a `QueryCommand` from an async reader with a 5-second timeout.
pub async fn read_command<R: AsyncReadExt + Unpin>(stream: &mut R) -> Result<QueryCommand> {
    let read_future = stream.read_u16();
    let timeout_duration = std::time::Duration::from_secs(5);

    match tokio::time::timeout(timeout_duration, read_future).await {
        Ok(Ok(command_val)) => {
            QueryCommand::from_u16(command_val).ok_or_else(|| anyhow!("Invalid command received"))
        }
        Ok(Err(e)) => Err(e.into()), // I/O error
        Err(_) => Err(anyhow!("Timed out reading command from stream")), // Timeout error
    }
}

/// Writes a `ClientHandshake` to an async writer.
pub async fn write_handshake<W: AsyncWriteExt + Unpin>(
    stream: &mut W,
    handshake: &ClientHandshake,
) -> Result<()> {
    let data = bincode::serialize(handshake)?;
    stream.write_u32(data.len() as u32).await?;
    stream.write_all(&data).await?;
    Ok(())
}

/// Reads a `ClientHandshake` from an async reader.
pub async fn read_handshake<R: AsyncReadExt + Unpin>(
    stream: &mut R,
) -> Result<Option<ClientHandshake>> {
    let len = match stream.read_u32().await {
        Ok(len) => len,
        Err(e) if e.kind() == std::io::ErrorKind::UnexpectedEof => return Ok(None),
        Err(e) => return Err(e.into()),
    };

    if len == 0 {
        return Ok(None);
    }

    let mut buffer = vec![0; len as usize];
    stream.read_exact(&mut buffer).await?;
    let handshake: ClientHandshake = bincode::deserialize(&buffer)?;
    Ok(Some(handshake))
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Cursor;

    #[tokio::test]
    async fn test_protocol_roundtrip() {
        let record = RawDataRecord {
            sent_nanos: 12345,
            rtt_nanos: 67890,
        };

        // 1. Write the record to a buffer
        let mut buffer = Vec::new();
        write_record(&mut buffer, &record).await.unwrap();

        // 2. Read the record back from the buffer
        let mut cursor = Cursor::new(buffer);
        let received_record = read_record(&mut cursor).await.unwrap().unwrap();

        // 3. Assert they are the same
        assert_eq!(record, received_record);
    }

    #[tokio::test]
    async fn test_read_empty_stream() {
        let mut empty: &[u8] = &[];
        let result = read_record(&mut empty).await.unwrap();
        assert!(result.is_none());
    }

    #[tokio::test]
    async fn test_batch_protocol_roundtrip() {
        let records = vec![
            RawDataRecord {
                sent_nanos: 1,
                rtt_nanos: 10,
            },
            RawDataRecord {
                sent_nanos: 2,
                rtt_nanos: 20,
            },
            RawDataRecord {
                sent_nanos: 3,
                rtt_nanos: u64::MAX,
            },
        ];

        // 1. Write the records to a buffer
        let mut buffer = Vec::new();
        write_records_batch(&mut buffer, &records).await.unwrap();

        // 2. Read the records back from the buffer
        let mut cursor = Cursor::new(buffer);
        let received_records = read_records_batch(&mut cursor).await.unwrap().unwrap();

        // 3. Assert they are the same
        assert_eq!(records, received_records);
    }

    #[tokio::test]
    async fn test_command_protocol_roundtrip() {
        let command = QueryCommand::GetLastMinute;

        // 1. Write the command to a buffer
        let mut buffer = Vec::new();
        write_command(&mut buffer, &command).await.unwrap();

        // 2. Read the command back from the buffer
        let mut cursor = Cursor::new(buffer);
        let received_command = read_command(&mut cursor).await.unwrap();

        // 3. Assert they are the same
        assert_eq!(command, received_command);
    }

    #[tokio::test]
    async fn test_handshake_protocol_roundtrip() {
        let handshake = ClientHandshake {
            source_hostname: "test-host".to_string(),
            target: "1.1.1.1".parse().unwrap(),
        };

        // 1. Write the handshake to a buffer
        let mut buffer = Vec::new();
        write_handshake(&mut buffer, &handshake).await.unwrap();

        // 2. Read the handshake back from the buffer
        let mut cursor = Cursor::new(buffer);
        let received_handshake = read_handshake(&mut cursor).await.unwrap().unwrap();

        // 3. Assert they are the same
        assert_eq!(handshake, received_handshake);
    }
}
