//! Defines the network protocol and data structures for communication between zzping services.

use anyhow::Result;
use serde::{Deserialize, Serialize};
use tokio::io::{AsyncReadExt, AsyncWriteExt};

/// The fundamental data structure for a single ping measurement.
///
/// This is the canonical format for data transfer between the collector and the database.
/// It is designed to be simple and efficient for JSON serialization.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
pub struct RawDataRecord {
    /// The timestamp when the ping was sent, as a UNIX timestamp in nanoseconds.
    ///
    /// This value is generated by the collector and represents the `Instant` the ICMP
    /// packet was sent, relative to a monotonic clock started at the beginning of the
    /// collector's session. The database service should treat this as a relative value
    /// and store it alongside an absolute timestamp for the session.
    pub sent_nanos: u64,
    /// The round-trip time in nanoseconds.
    ///
    /// If the packet was lost, this value will be `u64::MAX`. This is a sentinel value
    /// used to indicate packet loss, as `Option<u64>` would be less efficient for
    /// serialization and storage in the `chunked_v1` format.
    pub rtt_nanos: u64,
}

/// Writes a length-prefixed, JSON-serialized `RawDataRecord` to an async writer.
///
/// This function implements the sending side of the simple zzping network protocol.
/// The protocol is designed to be easy to implement in various clients and servers.
///
/// # Protocol Format
/// - 4 bytes: `u32` length of the following JSON payload, encoded in big-endian format.
/// - N bytes: The `RawDataRecord` struct, serialized as a JSON string.
///
/// # Arguments
/// * `stream` - An async writer, typically a `TcpStream`.
/// * `record` - The `RawDataRecord` to be sent.
pub async fn write_record<W: AsyncWriteExt + Unpin>(
    stream: &mut W,
    record: &RawDataRecord,
) -> Result<()> {
    let json_data = serde_json::to_vec(record)?;
    stream.write_u32(json_data.len() as u32).await?;
    stream.write_all(&json_data).await?;
    Ok(())
}

/// Reads a length-prefixed, JSON-serialized `RawDataRecord` from an async reader.
///
/// This function implements the receiving side of the simple zzping network protocol.
/// It handles reading the length prefix first, then reading the exact number of bytes
/// for the payload before deserializing.
///
/// # Returns
/// * `Ok(Some(RawDataRecord))` - If a record was successfully read and deserialized.
/// * `Ok(None)` - If the stream was closed cleanly by the peer (EOF).
/// * `Err(anyhow::Error)` - If there was an I/O error or a deserialization error.
pub async fn read_record<R: AsyncReadExt + Unpin>(stream: &mut R) -> Result<Option<RawDataRecord>> {
    let len = match stream.read_u32().await {
        Ok(len) => len,
        Err(e) if e.kind() == std::io::ErrorKind::UnexpectedEof => return Ok(None),
        Err(e) => return Err(e.into()),
    };

    if len == 0 {
        // This could be a keep-alive or a bug, but we'll treat it as a graceful end for now.
        return Ok(None);
    }

    let mut buffer = vec![0; len as usize];
    stream.read_exact(&mut buffer).await?;
    let record: RawDataRecord = serde_json::from_slice(&buffer)?;
    Ok(Some(record))
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Cursor;

    #[tokio::test]
    async fn test_protocol_roundtrip() {
        let record = RawDataRecord {
            sent_nanos: 12345,
            rtt_nanos: 67890,
        };

        // 1. Write the record to a buffer
        let mut buffer = Vec::new();
        write_record(&mut buffer, &record).await.unwrap();

        // 2. Read the record back from the buffer
        let mut cursor = Cursor::new(buffer);
        let received_record = read_record(&mut cursor).await.unwrap().unwrap();

        // 3. Assert they are the same
        assert_eq!(record, received_record);
    }

    #[tokio::test]
    async fn test_read_empty_stream() {
        let mut empty: &[u8] = &[];
        let result = read_record(&mut empty).await.unwrap();
        assert!(result.is_none());
    }
}
