//! Defines data structures used across the zzping crates.

use serde::{Deserialize, Serialize};

/// The fundamental data structure for a single ping measurement.
///
/// This is the canonical format for data transfer between the collector and the database.
/// It is designed to be simple and efficient for JSON serialization.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
pub struct RawDataRecord {
    /// The timestamp when the ping was sent, as a UNIX timestamp in nanoseconds.
    ///
    /// This value is generated by the collector and represents the `Instant` the ICMP
    /// packet was sent, relative to a monotonic clock started at the beginning of the
    /// collector's session. The database service should treat this as a relative value
    /// and store it alongside an absolute timestamp for the session.
    pub sent_nanos: u64,
    /// The round-trip time in nanoseconds.
    ///
    /// If the packet was lost, this value will be `u64::MAX`. This is a sentinel value
    /// used to indicate packet loss, as `Option<u64>` would be less efficient for
    /// serialization and storage in the `chunked_v1` format.
    pub rtt_nanos: u64,
}
