[package]
name = "zzping-gui"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "An egui-based GUI for viewing live and historical zzping data"

[dependencies]
# NOTE: All crates must define their dependencies in the workspace Cargo.toml for centralization
# ...   and instead use "cratename.workspace = true" to refer to it.
zzping-lib = { workspace = true }
zzping-proto = { workspace = true }
tokio = { workspace = true, features = ["net", "rt-multi-thread", "macros"] }
tonic = { workspace = true }
crossbeam-channel.workspace = true
log.workspace = true
serde_json.workspace = true
anyhow.workspace = true
byteorder.workspace = true
chrono.workspace = true
clap.workspace = true
eframe.workspace = true
egui.workspace = true

[dev-dependencies]
zzping-database = { workspace = true, features = ["test-utils"] }
tokio-stream = { workspace = true }
ntest.workspace = true
