[package]
name = "zzping-gui"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "A graphical interface that shows real-time network latency and packet loss graphs"

[dependencies]
zzping-lib.workspace = true
anyhow.workspace = true
async-std.workspace = true
chrono.workspace = true
clap.workspace = true
env_logger.workspace = true
iced.workspace = true
iced_native.workspace = true
log.workspace = true
rand.workspace = true
rmp.workspace = true
ron.workspace = true
rustdct.workspace = true
serde.workspace = true
thiserror.workspace = true
