[package]
name = "zzping-gui"
version = "0.2.2-beta2"
authors = ["Google LLC", "David Martinez Marti <deavidsedice@gmail.com>"]
edition = "2021"

[dependencies]
zzping-lib = { path = "../zzping-lib" }
iced = { version = "0.4", features = ["canvas"] }
iced_native = { version = "0.5" }
async-std = { version = "1.13", features = ["unstable"] }
rand = "0.9"
rmp = "0.8"
ron = "0.10"
clap = { version = "4.5", features = ["derive"] }
serde = "1.0"
anyhow = "1.0"
log = "0.4"
thiserror = "2.0.16"
env_logger = "0.11"
chrono = "0.4"
rustdct = "0.7"
