// File: zzping-proto/src/lib.rs

// This tells Rust to include the files generated by tonic-build.
// The `zzping` name comes from the `package zzping;` line in our .proto file.
pub mod zzping {
    #![allow(clippy::all)]
    tonic::include_proto!("zzping");
}

// Optional: Re-export the generated components for easier access from other crates.
pub use zzping::{
    ingestion_server::{Ingestion, IngestionServer},
    ingestion_client::IngestionClient,
    // ... and re-export all the message structs like RawDataRecord, IngestRequest, etc.
    HandshakeRequest, RawDataRecord, IngestRequest, WelcomeResponse, AckResponse, IngestResponse,
    QueryRequest, QueryResponse,
};
