// File: zzping-proto/src/lib.rs

// This tells Rust to include the files generated by tonic-build.
// The `zzping` name comes from the `package zzping;` line in our .proto file.
pub mod zzping {
    tonic::include_proto!("zzping");
}

// Optional: Re-export the generated components for easier access from other crates.
pub use zzping::{
    GetRecentDataRequest,
    GetRecentDataResponse,
    // Re-export all the message structs for the new Unary RPCs
    HeartbeatRequest,
    HeartbeatResponse,
    QueryRequest,
    QueryResponse,
    RawDataRecord,
    SendBatchRequest,
    SendBatchResponse,
    ingestion_client::IngestionClient,
    ingestion_server::{Ingestion, IngestionServer},
};
