[package]
name = "zzping-lib"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Common tooling for reading and writing messages for zzping binaries"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# NOTE: All crates must define their dependencies in the workspace Cargo.toml for centralization
# ...   and instead use "cratename.workspace = true" to refer to it.

anyhow.workspace = true
chrono.workspace = true
clap.workspace = true
env_logger.workspace = true
lazy_static.workspace = true
log.workspace = true
probability.workspace = true
rand.workspace = true
rmp.workspace = true
rustdct.workspace = true
rustfft.workspace = true
thiserror.workspace = true

# TODO: REMOVE THESE DEPENDENCIES - marked for removal
# These dependencies are old and should be replaced/removed in future versions
bit-vec = "0.6"          # TODO: Remove - for huffman, also for serializing
huffman-compress = "0.6" # TODO: Remove - 4 years old without updates
