[package]
name = "zzping-lib"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Shared library for zzping services"

[dependencies]
# NOTE: All crates must define their dependencies in the workspace Cargo.toml for centralization
# ...   and instead use "cratename.workspace = true" to refer to it.
anyhow.workspace = true
bincode.workspace = true
bitflags.workspace = true
byteorder.workspace = true
constriction.workspace = true
crc32fast.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
tokio = { workspace = true, features = ["full"] }
chrono = { workspace = true, features = ["serde"] }
log.workspace = true
crossbeam-channel = { workspace = true, optional = true }
bytes = { workspace = true, optional = true }
surge-ping = { workspace = true, optional = true }
clap = { workspace = true, features = ["derive"], optional = true }
eframe = { workspace = true, optional = true }
egui = { workspace = true, optional = true }
tempfile = { workspace = true, optional = true }
rand = { workspace = true, optional = true }
env_logger = { workspace = true, optional = true }
