[package]
name = "zzping-lib"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Common tooling for reading and writing messages for zzping binaries"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
bit-vec.workspace = true
chrono.workspace = true
clap.workspace = true
env_logger.workspace = true
huffman-compress.workspace = true
lazy_static.workspace = true
log.workspace = true
probability.workspace = true
rand.workspace = true
rmp.workspace = true
rustdct.workspace = true
rustfft.workspace = true
thiserror.workspace = true
