[package]
name = "zznet-peer-manager"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
# Phase 1 dependencies
actix = { workspace = true }
tokio = { workspace = true, features = ["sync"] }
tracing = { workspace = true }

# Auth types
zznet-api = { workspace = true }
zznet-router = { path = "../zznet-router" }

[dev-dependencies]
tokio = { workspace = true, features = ["sync"] }

[lints]
# This makes the crate inherit all lints defined in [workspace.lints]
workspace = true
