[workspace]
resolver = "2"
members = ["zzping-view", "zzping-press", "zzping-capture"]

[workspace.package]
version = "0.2.2-beta2"
authors = ["Google LLC", "David Martinez Marti <deavidsedice@gmail.com>"]
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/deavid/zzping"
description = "Tools to monitor home network latency and packet loss"

[workspace.dependencies]
# NOTE: All crates must define their dependencies in the workspace Cargo.toml for centralization
# ...   and instead use "cratename.workspace = true" to refer to it.

# Internal dependencies
zzping-lib = { path = "zzping-lib" }

# External dependencies
anyhow = "1.0"
async-std = { version = "1.13", features = ["unstable"] }
byteorder = "1.4"
chrono = "0.4"
clap = { version = "4.5", features = ["derive"] }
eframe = "0.32"
egui = "0.32"
env_logger = "0.11"
lazy_static = "1.5"
log = "0.4"
ping-rs = "0.1.2"
pnet = "0.35"
pnet_transport = "0.35"
pnet_macros_support = "0.35"
probability = "0.20"
rand = "0.9"
rmp = "0.8"
ron = "0.11"
rustdct = "0.7"
rustfft = "6.4"
serde = { version = "1.0", features = ["derive"] }
surge-ping = "0.8"
tempfile = "3.21"
thiserror = "2.0"
tokio = { version = "1", features = ["full"] }

# Dependencies for specific crates that haven't been centralized yet
rerun = "0.24"
constriction = "0.4"
bitflags = "2.9"
crc32fast = "1.3"

# Dev dependencies
criterion = { version = "0.7", features = ["html_reports"] }


[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 2

[profile.release]
debug = 2
