[workspace]
resolver = "2"
members = ["zzping-lib", "zzping-daemon", "zzping-gui", "zzping-capture"]

[workspace.package]
version = "0.2.2-beta2"
authors = ["Google LLC", "David Martinez Marti <deavidsedice@gmail.com>"]
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/deavid/zzping"
description = "Tools to monitor home network latency and packet loss"

[workspace.dependencies]
# NOTE: All crates must define their dependencies in the workspace Cargo.toml for centralization
# ...   and instead use "cratename.workspace = true" to refer to it.

# Internal dependencies
zzping-lib = { path = "zzping-lib" }

# External dependencies
anyhow = "1.0"
async-std = { version = "1.13", features = ["unstable"] }
bit-vec = "0.6"
chrono = "0.4"
clap = { version = "4.5", features = ["derive"] }
env_logger = "0.11"
# NOTE: huffman-compress is 4 years old without updates, and pulls bit-vec 0.6 to the project.
huffman-compress = "0.6"
iced = { version = "0.4", features = ["canvas"] }
iced_native = { version = "0.5" }
lazy_static = "1.5"
log = "0.4"
pnet = "0.35"
pnet_transport = "0.35"
pnet_macros_support = "0.35"
probability = "0.20"
rand = "0.9"
rmp = "0.8"
ron = "0.10"
rustdct = "0.7"
rustfft = "6.4"
serde = { version = "1.0", features = ["derive"] }
surge-ping = "0.8.2"
tempfile = "3.21"
thiserror = "2.0.16"
tokio = { version = "1", features = ["full"] }


[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 2

[profile.release]
debug = 2
