[package]
name = "zznet-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
zznet = { path = "../../components/zznet" }
zznet-api = { path = "../zznet-api" }
tokio = { workspace = true }
anyhow = { workspace = true }
log = { workspace = true }
futures = { workspace = true }
async-trait = { workspace = true }

[dev-dependencies]
ntest = { workspace = true }
env_logger = { workspace = true }
rmp-serde = { workspace = true }
