use crate::{
    auth::UserIdentity,
    config::{IntentConfig, load_intent_config},
    ingestion_item::IngestionItem,
    query::get_last_hour_records,
    scheduler::Scheduler,
};
use base64::{Engine as _, engine::general_purpose};
use dashmap::DashMap;
use log::{debug, error, info, warn};
use std::{collections::HashSet, net::IpAddr, sync::Arc};
use tokio::sync::mpsc;
use tonic::{Request, Response, Status};
use zzping_lib::auth::AuthToken;
use zzping_proto::zzping::{
    AnnouncePingsRequest, AnnouncePingsResponse, GetRecentDataRequest, GetRecentDataResponse,
    HeartbeatRequest, HeartbeatResponse, QueryRequest, QueryResponse, SendBatchRequest,
    SendBatchResponse, ingestion_server::Ingestion, send_batch_response,
};

/// A `tonic` interceptor that validates role-based authentication tokens.
///
/// This function is called for every incoming RPC request. It expects to find an
/// `authorization` header containing a `Bearer` token. The token itself is expected
/// to be a Base64-encoded JSON string that deserializes into an `AuthToken`.
///
/// If the token is valid, it creates a `UserIdentity` and attaches it to the
/// request's extensions for use by the actual RPC handler. If any step of this
/// process fails, it returns an `Unauthenticated` status, and the RPC handler
#[allow(clippy::result_large_err)]
pub fn check_auth<T>(mut req: Request<T>) -> Result<Request<T>, Status> {
    let token = req
        .metadata()
        .get("authorization")
        .and_then(|value| value.to_str().ok())
        .and_then(|str| str.strip_prefix("Bearer "));

    if let Some(token) = token {
        let decoded = general_purpose::STANDARD
            .decode(token)
            .map_err(|e| Status::unauthenticated(format!("Invalid token format: {e}")))?;

        let auth_token: AuthToken = serde_json::from_slice(&decoded)
            .map_err(|e| Status::unauthenticated(format!("Invalid token JSON: {e}")))?;

        let identity = UserIdentity {
            id: auth_token.sub,
            roles: auth_token.roles.into_iter().collect::<HashSet<String>>(),
        };

        req.extensions_mut().insert(identity);

        Ok(req)
    } else {
        Err(Status::unauthenticated("Missing auth token"))
    }
}

/// The core gRPC service for the zzping-database.
///
/// This struct implements the `Ingestion` trait generated by tonic and serves as the
/// single entry point for all network communication from collectors and clients.
///
/// It is designed to be mostly stateless on a per-call basis. All persistent state
/// is managed by the `scheduler` or stored on disk. The one exception is the
/// `collector_states` map, which is used for the `SendBatch` de-sync mechanism.
#[derive(Debug)]
pub struct IngestionServiceImpl {
    /// A send-only channel to the background storage engine task.
    ///
    /// Every batch of ping data that is successfully validated and accepted by the
    /// `send_batch` RPC is sent through this channel to be buffered and eventually
    /// written to a `.zzp1` file.
    storage_tx: mpsc::Sender<IngestionItem>,
    /// The path to the data directory, used for reading the `intent.ron` file
    /// and for querying historical data.
    data_dir: String,
    /// The shared, read-only configuration that dictates the desired state for
    /// all collectors. This is loaded once at startup.
    intent_config: Arc<IntentConfig>,
    /// A map tracking the last successfully acknowledged timestamp for each
    /// collector/target pair.
    ///
    /// This is used to implement the `OK`/`DESYNC` logic in the `SendBatch` RPC,
    /// ensuring that collectors and the database agree on the state of the data stream.
    /// The key is a tuple of `(collector_uuid, target_ip)`.
    collector_states: Arc<DashMap<(String, String), u64>>,
    /// The scheduler responsible for managing collector roles and orchestrating
    /// zero-downtime handoffs between them.
    scheduler: Arc<Scheduler>,
}

impl IngestionServiceImpl {
    /// Creates a new instance of the ingestion service.
    ///
    /// This function will panic if the `intent.ron` configuration file cannot be
    /// found or parsed, as the service cannot operate without it.
    pub fn new(storage_tx: mpsc::Sender<IngestionItem>, data_dir: String) -> Self {
        let intent_path = format!("{data_dir}/intent.ron");
        let intent_config = load_intent_config(&intent_path)
            .unwrap_or_else(|e| panic!("Failed to load intent config from {intent_path}: {e}"));
        info!("Loaded intent config: {intent_config:?}");

        Self {
            storage_tx,
            data_dir,
            intent_config: Arc::new(intent_config),
            collector_states: Arc::new(DashMap::new()),
            scheduler: Arc::new(Scheduler::new()),
        }
    }
}

#[tonic::async_trait]
impl Ingestion for IngestionServiceImpl {
    /// Handles a heartbeat from a collector.
    ///
    /// This RPC is the primary mechanism for a collector to learn its configuration
    /// and its role in the system (`Primary`, `Standby`, etc.). It also serves as
    /// the liveness probe for the scheduler to detect stale or crashed collectors.
    ///
    /// Requires the `"collector"` role.
    async fn heartbeat(
        &self,
        request: Request<HeartbeatRequest>,
    ) -> Result<Response<HeartbeatResponse>, Status> {
        let identity = request.extensions().get::<UserIdentity>().ok_or_else(|| {
            Status::internal(
                "Missing user identity. This should have been handled by the auth interceptor.",
            )
        })?;

        if !identity.has_role("collector") {
            return Err(Status::permission_denied("Missing 'collector' role."));
        }

        let request = request.into_inner();
        let (role, swap_at_nanos) = self.scheduler.process_heartbeat(
            &request.collector_uuid,
            request.pid,
            std::time::Instant::now(),
        );

        Ok(Response::new(HeartbeatResponse {
            targets: self.intent_config.targets.clone(),
            ping_rate_pps: self.intent_config.ping_rate_pps,
            role: role as i32,
            swap_at_nanos,
            last_fsynced_received_nanos: 0,
        }))
    }

    /// Receives a batch of ping data from a collector.
    ///
    /// This RPC implements an ACK/DESYNC mechanism to ensure that data is
    /// received in the correct order and to allow a collector to recover if it
    /// falls out of sync with the database's state.
    ///
    /// Requires the `"collector"` role.
    async fn send_batch(
        &self,
        request: Request<SendBatchRequest>,
    ) -> Result<Response<SendBatchResponse>, Status> {
        info!(
            "[DEBUG 1/4] send_batch received with {} records for collector '{}'",
            request.get_ref().records.len(),
            request.get_ref().collector_uuid
        );
        let identity = request.extensions().get::<UserIdentity>().ok_or_else(|| {
            Status::internal(
                "Missing user identity. This should have been handled by the auth interceptor.",
            )
        })?;

        if !identity.has_role("collector") {
            return Err(Status::permission_denied("Missing 'collector' role."));
        }

        let request = request.into_inner();
        let collector_id = request.collector_uuid;
        let target_ip_str = request.target_ip;
        let collector_believes_last_acked = request.collector_believes_last_acked_received_nanos;

        let target_ip: IpAddr = target_ip_str
            .parse()
            .map_err(|_| Status::invalid_argument("Invalid target_ip format"))?;

        let state_key = (collector_id.clone(), target_ip_str.clone());
        let mut collector_state = self.collector_states.entry(state_key).or_insert(0);

        let db_last_acked = *collector_state;

        if db_last_acked != collector_believes_last_acked {
            warn!(
                "Collector {collector_id} for target {target_ip_str} is out of sync. DB acked: {db_last_acked}, collector believed: {collector_believes_last_acked}"
            );
            return Ok(Response::new(SendBatchResponse {
                status: send_batch_response::Status::Desync as i32,
                database_confirms_last_acked_received_nanos: db_last_acked,
            }));
        }

        let mut last_sent_nanos = db_last_acked;
        for record in request.records {
            if record.sent_nanos <= db_last_acked {
                warn!(
                    "Collector {collector_id} sent record for {target_ip_str} with old timestamp, ignoring."
                );
                continue;
            }
            last_sent_nanos = record.sent_nanos;

            // This is the core fix: send the item to the storage engine.
            let item = IngestionItem {
                source_hostname: collector_id.clone(),
                target: target_ip,
                record: zzping_lib::protocol::RawDataRecord {
                    sent_nanos: record.sent_nanos,
                    rtt_nanos: record.rtt_nanos,
                },
            };
            info!("[DEBUG 2/4] Constructed IngestionItem: {item:?}");
            if self.storage_tx.send(item).await.is_err() {
                error!("Storage task channel closed. This is a fatal error.");
                return Err(Status::internal("Storage engine has shut down."));
            }
        }

        *collector_state = last_sent_nanos;

        Ok(Response::new(SendBatchResponse {
            status: send_batch_response::Status::Ok as i32,
            database_confirms_last_acked_received_nanos: last_sent_nanos,
        }))
    }

    /// Allows a newly promoted `Primary` collector to seed its buffer with recent data.
    ///
    /// When a `Standby` collector is promoted, its local buffer of ping results
    /// is empty. To ensure a seamless handoff without data gaps, it calls this
    /// RPC to fetch the most recent data points that the previous `Primary` had
    /// successfully sent.
    ///
    /// Requires the `"collector"` role.
    async fn get_recent_data(
        &self,
        request: Request<GetRecentDataRequest>,
    ) -> Result<Response<GetRecentDataResponse>, Status> {
        let identity = request.extensions().get::<UserIdentity>().ok_or_else(|| {
            Status::internal(
                "Missing user identity. This should have been handled by the auth interceptor.",
            )
        })?;

        if !identity.has_role("collector") {
            return Err(Status::permission_denied("Missing 'collector' role."));
        }

        info!(
            "get_recent_data called by '{}', returning empty response for now.",
            identity.id
        );
        Ok(Response::new(GetRecentDataResponse {
            records: vec![],
            database_confirms_last_acked_received_nanos: 0,
        }))
    }

    /// Allows a client (like `zzping-gui`) to query for historical data.
    ///
    /// This is a simple implementation that finds the most recent `.zzp1` data
    /// file and returns all records from the last hour found within it.
    ///
    /// Requires the `"reader"` role.
    async fn query_data(
        &self,
        request: Request<QueryRequest>,
    ) -> Result<Response<QueryResponse>, Status> {
        let identity = request.extensions().get::<UserIdentity>().ok_or_else(|| {
            Status::internal(
                "Missing user identity. This should have been handled by the auth interceptor.",
            )
        })?;

        if !identity.has_role("reader") {
            return Err(Status::permission_denied("Missing 'reader' role."));
        }

        let records = get_last_hour_records(&self.data_dir)
            .map_err(|e| Status::internal(e.to_string()))?
            .into_iter()
            .map(|r| zzping_proto::zzping::RawDataRecord {
                sent_nanos: r.sent_nanos,
                rtt_nanos: r.rtt_nanos,
            })
            .collect();

        Ok(Response::new(QueryResponse { records }))
    }

    /// Receives a fire-and-forget announcement of pings being sent.
    ///
    /// This is used for low-latency, real-time visualization in the GUI. The data
    /// is not considered durable and may be dropped. The database is expected to
    /// hold it in a short-lived in-memory cache.
    ///
    /// Requires the `"collector"` role.
    async fn announce_pings(
        &self,
        request: Request<AnnouncePingsRequest>,
    ) -> Result<Response<AnnouncePingsResponse>, Status> {
        let identity = request.extensions().get::<UserIdentity>().ok_or_else(|| {
            Status::internal(
                "Missing user identity. This should have been handled by the auth interceptor.",
            )
        })?;

        if !identity.has_role("collector") {
            return Err(Status::permission_denied("Missing 'collector' role."));
        }

        // For now, we just accept the request and do nothing with it.
        // A future implementation would add this to a live-data cache.
        debug!("Received AnnouncePings from '{}'", identity.id);

        Ok(Response::new(AnnouncePingsResponse {}))
    }

    type SubscribeToCommandsStream = std::pin::Pin<
        Box<dyn tokio_stream::Stream<Item = Result<zzping_proto::zzping::Command, Status>> + Send>,
    >;

    async fn subscribe_to_commands(
        &self,
        request: Request<zzping_proto::zzping::CommandRequest>,
    ) -> Result<Response<Self::SubscribeToCommandsStream>, Status> {
        let identity = request.extensions().get::<UserIdentity>().ok_or_else(|| {
            Status::internal(
                "Missing user identity. This should have been handled by the auth interceptor.",
            )
        })?;

        if !identity.has_role("collector") {
            return Err(Status::permission_denied("Missing 'collector' role."));
        }

        info!("Collector '{}' subscribed to command stream.", identity.id);

        // For now, we return an empty stream that closes immediately.
        let (tx, rx) = mpsc::channel(1);
        let stream = tokio_stream::wrappers::ReceiverStream::new(rx);
        // Keep the sender alive for now, otherwise the stream closes immediately.
        // A real implementation would store this sender somewhere.
        tokio::spawn(async move {
            let _sender = tx;
        });

        Ok(Response::new(Box::pin(stream)))
    }
}

#[cfg(feature = "test-utils")]
use std::time::Duration;
#[cfg(feature = "test-utils")]
use tokio::task::JoinHandle;
#[cfg(feature = "test-utils")]
use tokio_stream::wrappers::TcpListenerStream;
#[cfg(feature = "test-utils")]
use zzping_proto::zzping::ingestion_server::IngestionServer;

#[cfg(feature = "test-utils")]
pub async fn spawn_test_server(data_dir: String) -> (std::net::SocketAddr, JoinHandle<()>) {
    let listener = tokio::time::timeout(
        Duration::from_millis(500),
        tokio::net::TcpListener::bind("127.0.0.1:0"),
    )
    .await
    .expect("Listener bind timed out")
    .unwrap();

    let addr = listener.local_addr().unwrap();
    let (tx, _) = mpsc::channel(100);
    let service = IngestionServiceImpl::new(tx, data_dir);
    let server = IngestionServer::with_interceptor(service, check_auth);

    let handle = tokio::spawn(async move {
        let _ = tokio::time::timeout(
            Duration::from_secs(5),
            tonic::transport::Server::builder()
                .add_service(server)
                .serve_with_incoming(TcpListenerStream::new(listener)),
        )
        .await;
    });

    (addr, handle)
}

#[cfg(test)]
mod tests {
    use ntest::timeout;
    use super::*;
    use crate::auth::generate_test_token;
    use std::io::Write;
    use tempfile::tempdir;
    use zzping_proto::zzping::{RawDataRecord, ingestion_client::IngestionClient};

    #[test]
    #[timeout(100)]
    fn test_check_auth() {
        // Good token
        let token = generate_test_token("test-user", &["reader", "collector"]);
        let mut good_req = Request::new(());
        good_req
            .metadata_mut()
            .insert("authorization", format!("Bearer {token}").parse().unwrap());
        let result = check_auth(good_req);
        assert!(result.is_ok());
        let identity = result
            .unwrap()
            .extensions()
            .get::<UserIdentity>()
            .unwrap()
            .clone();
        assert_eq!(identity.id, "test-user");
        assert!(identity.has_role("reader"));
        assert!(identity.has_role("collector"));
        assert!(!identity.has_role("admin"));

        // Bad tokens
        let mut bad_req_invalid = Request::new(());
        bad_req_invalid
            .metadata_mut()
            .insert("authorization", "Bearer not-base64".parse().unwrap());
        assert!(check_auth(bad_req_invalid).is_err());

        let bad_req_missing = Request::new(());
        assert!(check_auth(bad_req_missing).is_err());
    }

    #[tokio::test]
    #[timeout(1000)]
    async fn test_query_data_permission() {
        let temp_dir = tempdir().unwrap();
        let data_dir = temp_dir.path();
        let intent_path = data_dir.join("intent.ron");
        let mut file = std::fs::File::create(intent_path).unwrap();
        write!(file, "(ping_rate_pps: 1, targets: [])").unwrap();

        let (server_addr, server_handle) =
            spawn_test_server(temp_dir.path().to_str().unwrap().to_string()).await;

        let mut client = IngestionClient::connect(format!("http://{server_addr}"))
            .await
            .unwrap();

        // Test with correct role
        let token = generate_test_token("test-reader", &["reader"]);
        let mut request = Request::new(QueryRequest {});
        request
            .metadata_mut()
            .insert("authorization", format!("Bearer {token}").parse().unwrap());
        let response = client.query_data(request).await;
        assert!(response.is_ok());

        // Test with incorrect role
        let token = generate_test_token("test-collector", &["collector"]);
        let mut request = Request::new(QueryRequest {});
        request
            .metadata_mut()
            .insert("authorization", format!("Bearer {token}").parse().unwrap());
        let response = client.query_data(request).await;
        assert_eq!(
            response.err().unwrap().code(),
            tonic::Code::PermissionDenied
        );

        server_handle.abort();
    }

    #[tokio::test]
    #[timeout(1000)]
    async fn test_heartbeat_rpc_permission() {
        let temp_dir = tempdir().unwrap();
        let intent_path = temp_dir.path().join("intent.ron");
        let mut file = std::fs::File::create(intent_path).unwrap();
        write!(file, "(ping_rate_pps: 50, targets: [])").unwrap();
        let (server_addr, server_handle) =
            spawn_test_server(temp_dir.path().to_str().unwrap().to_string()).await;

        let mut client = IngestionClient::connect(format!("http://{server_addr}"))
            .await
            .unwrap();

        // Test with correct role
        let token = generate_test_token("test-collector", &["collector"]);
        let mut request = Request::new(HeartbeatRequest {
            collector_uuid: "test-collector".to_string(),
            pid: 1234,
            current_role: 0,
            buffer_record_count: 0,
            last_fatal_error: "".to_string(),
            last_processed_command_id: 0,
        });
        request
            .metadata_mut()
            .insert("authorization", format!("Bearer {token}").parse().unwrap());
        let response = client.heartbeat(request).await;
        assert!(response.is_ok());

        // Test with incorrect role
        let token = generate_test_token("test-reader", &["reader"]);
        let mut request = Request::new(HeartbeatRequest {
            collector_uuid: "test-collector".to_string(),
            pid: 1234,
            current_role: 0,
            buffer_record_count: 0,
            last_fatal_error: "".to_string(),
            last_processed_command_id: 0,
        });
        request
            .metadata_mut()
            .insert("authorization", format!("Bearer {token}").parse().unwrap());
        let response = client.heartbeat(request).await;
        assert_eq!(
            response.err().unwrap().code(),
            tonic::Code::PermissionDenied
        );

        server_handle.abort();
    }

    fn create_test_service_with_receiver() -> (IngestionServiceImpl, mpsc::Receiver<IngestionItem>)
    {
        let (tx, rx) = mpsc::channel(100);
        (
            IngestionServiceImpl {
                storage_tx: tx,
                data_dir: "".to_string(),
                intent_config: Arc::new(IntentConfig {
                    ping_rate_pps: 0,
                    targets: vec![],
                }),
                collector_states: Arc::new(DashMap::new()),
                scheduler: Arc::new(Scheduler::new()),
            },
            rx,
        )
    }

    fn create_authed_request<T>(payload: T, sub: &str, roles: &[&str]) -> Request<T> {
        let mut request = Request::new(payload);
        let identity = UserIdentity {
            id: sub.to_string(),
            roles: roles.iter().map(|s| s.to_string()).collect(),
        };
        request.extensions_mut().insert(identity);
        request
    }

    #[tokio::test]
    #[timeout(100)]
    async fn test_sendbatch_accepts_good_data() {
        let (service, mut item_rx) = create_test_service_with_receiver();
        tokio::spawn(async move { while item_rx.recv().await.is_some() {} });

        let state_key = ("collector-1".to_string(), "1.1.1.1".to_string());
        service.collector_states.insert(state_key.clone(), 100);

        let payload = SendBatchRequest {
            collector_uuid: "collector-1".to_string(),
            target_ip: "1.1.1.1".to_string(),
            collector_believes_last_acked_received_nanos: 100,
            records: vec![
                RawDataRecord {
                    sent_nanos: 101,
                    rtt_nanos: 10,
                },
                RawDataRecord {
                    sent_nanos: 102,
                    rtt_nanos: 11,
                },
            ],
        };
        let request = create_authed_request(payload, "collector-1", &["collector"]);

        let response = service.send_batch(request).await.unwrap().into_inner();
        assert_eq!(response.status, send_batch_response::Status::Ok as i32);
        assert_eq!(response.database_confirms_last_acked_received_nanos, 102);
        assert_eq!(*service.collector_states.get(&state_key).unwrap(), 102);
    }

    #[tokio::test]
    #[timeout(100)]
    async fn test_sendbatch_rejects_desync_data() {
        let (service, mut item_rx) = create_test_service_with_receiver();
        tokio::spawn(async move { while item_rx.recv().await.is_some() {} });

        let state_key = ("collector-1".to_string(), "1.1.1.1".to_string());
        service.collector_states.insert(state_key.clone(), 100);

        let payload = SendBatchRequest {
            collector_uuid: "collector-1".to_string(),
            target_ip: "1.1.1.1".to_string(),
            collector_believes_last_acked_received_nanos: 99,
            records: vec![RawDataRecord {
                sent_nanos: 101,
                rtt_nanos: 10,
            }],
        };
        let request = create_authed_request(payload, "collector-1", &["collector"]);

        let response = service.send_batch(request).await.unwrap().into_inner();
        assert_eq!(response.status, send_batch_response::Status::Desync as i32);
        assert_eq!(response.database_confirms_last_acked_received_nanos, 100);
        assert_eq!(*service.collector_states.get(&state_key).unwrap(), 100);
    }
}
