[package]
name = "intent-config"
version = "0.1.0"
edition = "2021"

[dependencies]
zzchorale = { path = "../zzchorale" }
zznet-api = { path = "../../common/zznet-api" }
zznet = { path = "../zznet" }
tokio = { workspace = true, features = ["sync"] }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
log = { workspace = true }
futures = "0.3"
async-trait = { workspace = true }

[dev-dependencies]
zznet = { path = "../zznet" }
env_logger = { workspace = true }
ntest = { workspace = true }
