[package]
name = "zzping-collector"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Collector service for zzping"

[dependencies]
# NOTE: All crates must define their dependencies in the workspace Cargo.toml for centralization
# ...   and instead use "cratename.workspace = true" to refer to it.
zzping-lib = { workspace = true }
zzping-proto = { workspace = true }
anyhow.workspace = true
async-trait.workspace = true
base64.workspace = true
bincode.workspace = true
bytes.workspace = true
chrono = { workspace = true, features = ["serde"] }
clap = { workspace = true, features = ["derive"] }
env_logger.workspace = true
log.workspace = true
rand.workspace = true
ron = { workspace = true }
serde.workspace = true
serde_json.workspace = true
surge-ping.workspace = true
tokio = { workspace = true, features = ["net", "rt-multi-thread", "macros", "io-util", "sync", "time"] }
tokio-stream = { workspace = true }
tonic = { workspace = true }

[dev-dependencies]
byteorder.workspace = true
ntest.workspace = true
tempfile.workspace = true
zzping-database = { workspace = true, features = ["test-utils"] }
