[package]
name = "zzping-cli"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "A command-line tool for inspecting zzping data files."

[dependencies]
zzping-lib = { workspace = true }
clap = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["full"] }
anyhow.workspace = true
log.workspace = true
chrono.workspace = true
env_logger.workspace = true
