[package]
name = "zzping-capture"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "A command-line tool to perform high-frequency ICMP pings and save the raw results."

[dependencies]
anyhow = { workspace = true }
tokio = { workspace = true }
surge-ping = { workspace = true }
clap = { workspace = true }
chrono = { workspace = true }
rand = { workspace = true }
