[package]
name = "zznet-router"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
# Async runtime
tokio = { workspace = true, features = ["sync", "macros"] }
tracing = { workspace = true }
actix = { workspace = true }
async-trait.workspace = true
thiserror.workspace = true
serde = { workspace = true, features = ["derive"] }
rmp-serde = { workspace = true }

# Internal dependencies
zznet-api = { workspace = true }
zznet-room = { workspace = true }

[dev-dependencies]
actix-rt = { workspace = true }

[lints]
# This makes the crate inherit all lints defined in [workspace.lints]
workspace = true
