[package]
name = "zznet-demo"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Integration tests and examples for the zznet framework"

[lints]
workspace = true

[dependencies]
actix.workspace = true
actix-rt.workspace = true
anyhow.workspace = true
tokio.workspace = true
serde.workspace = true
tracing.workspace = true
thiserror.workspace = true
async-trait.workspace = true
rmp-serde.workspace = true
zznet-api.workspace = true
zznet-hello.workspace = true
zznet-room.workspace = true
zznet-router.workspace = true
bytes.workspace = true

[dev-dependencies]
ntest.workspace = true
tempfile.workspace = true
tokio = { workspace = true, features = ["full"] }
tracing-subscriber.workspace = true
zzping-test-utils = { workspace = true }
ron.workspace = true
