[package]
name = "zzping-daemon"
version = "0.2.2-beta1"
authors = ["Google LLC", "David Martinez Marti <deavidsedice@gmail.com>"]
edition = "2018"

[dependencies]
zzping-lib = { path = "../zzping-lib" }
env_logger = "0.8.1"
log = "0.4.11"
pnet = "0.26"
pnet_macros_support = "0.26"
rand = "0.7"
rmp = "0.8.9"
ron = "0.6.2"
clap = "3.0.0-beta.2"
serde = "1.0.117"
chrono = "0.4"
tempfile = "3"


[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
debug = 2

[profile.release]
debug = 2
