[package]
name = "zzping-daemon"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "A daemon that pings hosts and logs network latency and packet loss statistics"

[dependencies]
# NOTE: All crates must define their dependencies in the workspace Cargo.toml for centralization
# ...   and instead use "cratename.workspace = true" to refer to it.

zzping-lib.workspace = true
anyhow.workspace = true
chrono.workspace = true
clap.workspace = true
env_logger.workspace = true
log.workspace = true
pnet.workspace = true
pnet_transport.workspace = true
pnet_macros_support.workspace = true
rand.workspace = true
rmp.workspace = true
ron.workspace = true
serde.workspace = true
tempfile.workspace = true
