[package]
name = "zzping-test-utils"
version = "0.1.0"
edition = "2024"
authors = ["zzping-dev"]

[lib]
name = "zzping_test_utils"
path = "src/lib.rs"

[dependencies]
zznet-session = { path = "../../net/zznet-session" }
tokio = { workspace = true }
zznet-auth = { workspace = true }

[dev-dependencies]
# none
