[package]
name = "zzping-press"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "A tool for stress testing and network performance analysis"

[dependencies]
# NOTE: All crates must define their dependencies in the workspace Cargo.toml for centralization
# ...   and instead use "cratename.workspace = true" to refer to it.

anyhow.workspace = true
clap.workspace = true
rerun.workspace = true
constriction.workspace = true
byteorder.workspace = true
bitflags.workspace = true
rand.workspace = true
crc32fast.workspace = true

[dev-dependencies]
chrono.workspace = true
criterion.workspace = true

[[bench]]
name = "chunked_v1_benches"
harness = false
